### ISSUE TITLE
Documentation needed for v.0.3.0b1

### ISSUE THREAD

**Issue by crawfordcomeaux** [connectordb/connectordb.github.io#6]
- [ ] Expand README
  - [x] How to document
  - [ ] How to connect with contributors/users
  - [ ] How to propose changes
  - [ ] How to talk about the issues
- [ ] Explain roles & permissions with examples
- [ ] Intro tutorial from clean install to gathering/creating data via all available paths
- [ ] Explain uses for stream datatypes & give guidelines for naming
- [ ] TBD

**Comment by dkumor** [comment]
The website has moved to https://github.com/connectordb/connectordb.io - if you think this issue is still relevant, please reopen it there.
